name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[release]
        pip install build twine
    
    - name: Build release package
      run: |
        python -m build --sdist --wheel
    
    - name: Run security scan
      run: |
        bandit -r src/ --severity-level high
        safety check
    
    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: sigfile-cli-release
        path: dist/
    
    - name: Publish to PyPI
      if: github.event_name == 'release' && github.event.action == 'published'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*

  performance:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[release]
        pip install pytest-benchmark
    
    - name: Run performance tests
      run: |
        pytest --benchmark-only
    
    - name: Upload performance results
      uses: actions/upload-artifact@v2
      with:
        name: performance-results
        path: .benchmarks/

  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[release]
        pip install bandit safety
    
    - name: Run security checks
      run: |
        bandit -r src/ --severity-level high
        safety check
    
    - name: Upload security report
      uses: actions/upload-artifact@v2
      with:
        name: security-report
        path: security-report.txt 